// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-projects.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
import { projects, CATEGORIES } from "npm:@/data/projects";
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List portfolio projects",
  description: "Return a list of Boopathi Raja's portfolio projects with slug, name, tagline, category, status, year, and live URL. Optionally filter by category, status, or featured flag.",
  inputSchema: {
    category: z.enum(CATEGORIES).optional().describe("Filter by category"),
    status: z.enum(["Production", "MVP", "Prototype"]).optional().describe("Filter by project status"),
    featuredOnly: z.boolean().optional().describe("Only return featured projects")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, status, featuredOnly }) => {
    const filtered = projects.filter((p) => {
      if (category && p.category !== category) return false;
      if (status && p.status !== status) return false;
      if (featuredOnly && !p.featured) return false;
      return true;
    });
    const summary = filtered.map((p) => ({
      slug: p.slug,
      name: p.name,
      tagline: p.tagline,
      category: p.category,
      status: p.status,
      year: p.year,
      liveUrl: p.liveUrl ?? null,
      featured: p.featured ?? false
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { count: summary.length, projects: summary }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
import { projects as projects2 } from "npm:@/data/projects";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project details",
  description: "Return full details for a single portfolio project by slug, including problem, features, stack, architecture, highlight, metrics, evidence, gaps, and live URL.",
  inputSchema: {
    slug: z2.string().min(1).describe("Project slug (e.g. 'steel-flow', 'nexq')")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const project = projects2.find((p) => p.slug === slug);
    if (!project) {
      return {
        content: [
          {
            type: "text",
            text: `No project found with slug "${slug}". Use list_projects to see available slugs.`
          }
        ],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(project, null, 2) }],
      structuredContent: { project }
    };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_profile_default = defineTool3({
  name: "get_profile",
  title: "Get Boopathi Raja's profile",
  description: "Return Boopathi Raja's public profile: name, role, bio, focus areas, and links to portfolio site and live projects.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const profile = {
      name: "Boopathi Raja",
      role: "Vibe Coder",
      tagline: "Full-stack builder shipping production apps for real clients \u2014 POS, marketplaces, AI tools.",
      focus: [
        "Client work (POS, retail, bakery, exam prep)",
        "AI-native products",
        "Multi-tenant SaaS with Supabase + RLS",
        "TanStack Start / Next.js / React"
      ],
      links: {
        portfolio: "https://boopathiraja.dev",
        published: "https://code-and-charm-folio.lovable.app"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: profile
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "boopathiraja-portfolio-mcp",
  title: "Boopathi Raja \u2014 Portfolio MCP",
  version: "0.1.0",
  instructions: "Public tools for Boopathi Raja's portfolio. Use `get_profile` for bio and links, `list_projects` to browse projects (optionally filtered by category, status, or featured), and `get_project` for full case-study details on a specific project by slug.",
  tools: [list_projects_default, get_project_default, get_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
